### ISSUE TITLE
import uuid from 'uuid'; not working!

### ISSUE THREAD

**Issue by iamaakashbasnet** [bradtraversy/react_crash_todo#14]
Hello! Importing is not working for uuid. It says :

> Failed to compile.
> ./src/App.js
> Attempted import error: 'uuid' does not contain a default export (imported as 'uuid').

But this is working :
const uuid = require('uuid');

Why it is showing error?

**Comment by adisen** [comment]
As the error says, there is not default export with that name. This is the way to use it:

`import { v4 as uuidv4 } from 'uuid';`

Check https://www.npmjs.com/package/uuid

**Comment by iamaakashbasnet** [comment]
Oh yes! Now its working! Thanks!

**Comment by adisen** [comment]
You can close the issue now...

**Comment by iamaakashbasnet** [comment]
Okay!
