### ISSUE TITLE
Error when adding multiples todos (Getting id: 201) - Fixing

### ISSUE THREAD

**Issue by gughog** [bradtraversy/react_crash_todo#2]
Hello Brad, first thanks for the great tutorial crash course, but the final code has some issues about the add new todo process. The new todos had same ids of '201', in my researchs i've found that this is a http code related. Searching in the comments i've found a fix from a user "David Ernest"
([His channel](https://www.youtube.com/channel/UCYGzexv1ZcNrKikHYpFw_yg)). The fix is listed below:

In App.js, at axios.post '.then' for appTodo change to this:
```javascript
.then(res => {
      res.data.id = uuid();  //or uuid.v4()
      this.setState({ todos: [...this.state.todos, res.data] });
    }); 
```
This should make your code work because this manually overwriting the id property that comes back from the JSON Placeholder API, as the Youtube user said!

Hope this help!

**Comment by Rao-Mustafa** [comment]
well its correct and proper way is 

`.then(res => {
  res.data.id=this.state.todo.length+1;
  this.setState({ todo: [...this.state.todo , res.data]  })})`
